src/solver/clause.rs, src/solver/mod.rs, tests/solver.rs
The original bug was caused by adding a conflicting `requires` clause, yet failing to detect and handle the conflict. This commit introduces a clearer separation between: adding new clauses, detecting conflicts, and handling said conflicts.
Closes #13 
Closes https://github.com/prefix-dev/rip/issues/75
=> fix: incremental solving (rip issue #75)

src/solver/decision_tracker.rs, src/solver/mod.rs
Note for reviewers: this PR assumes that #15 has been merged. Ideally, I'd take my `fix-nested-deps-issue` branch as a base, but then the PR would end up being created in my own repository. Fortunately the whole code is in a single commit, so you can have a look at the last commit's diff (or wait till #15 is merged).
=> Remove fixed assignments

src/lib.rs, src/solver/clause.rs, src/solver/mod.rs, tests/solver.rs
Note: this assumes #15 and #16 are merged.
Question: should we make it possible for the provider to tell the reason why the dependencies are unknown? For instance, a string where we can put the contents of [this panic](https://github.com/prefix-dev/rip/blob/25e2344e62804dab039a1c806b7489c3779f3e47/crates/rattler_installs_packages/src/resolve/dependency_provider.rs#L475-L478)
Closes #14
=> Allow returning "unknown dependencies" in `get_dependencies`

src/lib.rs, src/problem.rs, src/solver/cache.rs, src/solver/mod.rs, tests/snapshots/solver__resolve_and_cancel.snap, tests/solver.rs
Introduces a `should_cancel_with_value` method in `DependencyProvider`,
that returns an `Option<Box<dyn Any>>`. This method is called at the
beginning of each unit propagation round and before potentially blocking
operations (like [Self::get_dependencies] and [Self::get_candidates]).
If `should_cancel_with_value` returns `Some(...)`,
propagation is interrupted and the solver returns
`Err(UnsolvableOrCancelled::Cancelled(...))`, bubbling up the value to
the library user (this way you can handle any additional details
surrounding the cancellation outside of the solver).
Closes #8.
- `SolverCache::provider` is now `pub(crate)`. Is that all right?
- The current design requires implementors of `DependencyProvider` to use interior mutability to track cancellation. I think that's reasonable, …
=> feat: allow cancelling the solving process

src/solver/mod.rs
The formatting is a bit unfortunate, but that's what `cargo fmt` makes of it
=> fix: remove unnecessary aggressive assertion

src/solver/mod.rs
Fixes, bug mentioned in: https://github.com/prefix-dev/rip/issues/174
Does not fix the issue, but we think this is the behavior we want.
=> feat: continue when encountering unknown depencies

src/problem.rs, tests/snapshots/solver__merge_excluded.snap
The previous implementation represented `excluded` as an incoming conflict, thereby preventing the merging algorithm from grouping excludes together. This PR represents `excluded` as an outgoing conflict, which allows the merging algorithm to do its job. See the modified snapshot for details.
This addresses one of the issues in #9.
Below are some pictures of the internal graph, in case you are curious.
=> fix: merge similar excluded messages when unsat

src/problem.rs, tests/snapshots/solver__excluded.snap, tests/snapshots/solver__merge_excluded.snap, tests/snapshots/solver__merge_installable.snap, tests/snapshots/solver__merge_installable_non_continuous_range.snap, tests/snapshots/solver__root_excluded.snap, tests/snapshots/solver__unsat_after_backtracking.snap, tests/snapshots/solver__unsat_applies_graph_compression.snap, tests/snapshots/solver__unsat_bluesky_conflict.snap, tests/snapshots/solver__unsat_constrains.snap, tests/snapshots/solver__unsat_constrains_2.snap, tests/snapshots/solver__unsat_incompatible_root_requirements.snap, tests/snapshots/solver__unsat_locked_and_excluded.snap, tests/snapshots/solver__unsat_no_candidates_for_child_1.snap, tests/snapshots/solver__unsat_no_candidates_for_child_2.snap, tests/snapshots/solver__unsat_pubgrub_article.snap
I extracted the new indentation code from #28 
**Old**
```
The following packages are incompatible
|-- a * cannot be installed because there are no viable options:
|-- a 2 would require
|-- b *, which cannot be installed because there are no viable options:
|-- b 1 is excluded because it is externally excluded
|-- a 1 would require
|-- c *, which cannot be installed because there are no viable options:
|-- c 1 is excluded because it is externally excluded
```
**New**
```
The following packages are incompatible
└─ a * cannot be installed because there are no viable options:
├─ a 2 would require
│  └─ b *, which cannot be installed because there are no viable options:
│     └─ b 1 is excluded because it is externally excluded
└─ a 1 would require
└─ c *, which cannot be installed because …
```
=> feat: improved indentation in error messages

src/lib.rs
We no longer need the `Ord` trait for versions, sorting is handled by the `DependencyProvider`.
=> fix: relax ord constraint

Cargo.toml, src/internal/arena.rs, src/internal/frozen_copy_map.rs, src/internal/id.rs, src/internal/mapping.rs, src/pool.rs, src/problem.rs, src/solver/cache.rs, src/solver/clause.rs, src/solver/decision_map.rs, src/solver/mod.rs, tests/solver.rs
* Reduce the size of some datastructures
* Use `ahash` for hash tables
Provides a 1-5% performance increase.
=> perf: small memory performance optimizations

CHANGELOG.md, Cargo.toml
* `resolvo`: 0.5.0 -> 0.6.0
<blockquote>
- remove `Pool` from API ([#40](https://github.com/mamba-org/resolvo/pull/40))
</blockquote>
</p></details>
---
=> chore: release v0.6.0

.clang-format, .gitattributes, .github/workflows/cpp-test.yml, .github/workflows/rust-compile.yml, .gitignore, CMakeLists.txt, Cargo.toml, cpp/CMakeLists.txt, cpp/Cargo.toml, cpp/build.rs, cpp/include/resolvo.h, cpp/include/resolvo_dependency_provider.h, cpp/include/resolvo_pool.h, cpp/include/resolvo_slice.h, cpp/include/resolvo_string.h, cpp/include/resolvo_vector.h, cpp/src/lib.rs, cpp/src/slice.rs, cpp/src/string.rs, cpp/src/vector.rs, cpp/tests/CMakeLists.txt, cpp/tests/solve.cpp, cpp/tests/string.cpp, cpp/tests/vector.cpp, pixi.lock, pixi.toml, src/internal/id.rs
Builds on #40 
This PR adds preliminary C++ bindings. There is still stuff missing with regards to documentation and a proper CMake install but the functionality is there. A test that shows how to use the bindings can be found here: https://github.com/baszalmstra/resolvo/blob/feat/cpp_bindings/cpp/tests/solve.cpp#L165
My C++ is quite rusty (pun intended) so feedback is definitely welcome!
I added a `pixi.toml` to quickly get started with the code. Simply run:
```
pixi run test-cpp
```
to build and run the C++ tests.
=> feat: c++ bindings

.github/workflows/cpp-test.yml, .github/workflows/rust-compile.yml, .gitignore, CMakeLists.txt, Cargo.toml, cpp/CMakeLists.txt, cpp/Cargo.toml, cpp/cmake/ResolvoConfig.cmake.in, cpp/tests/CMakeLists.txt, pixi.lock, pixi.toml, recipe/recipe.yaml, recipe/variant_config.yaml, tools/solve-snapshot/Cargo.toml
This PR adds a recipe and some missing CMake code to create a conda package for the C++ bindings.
=> feat: add rattler-build recipe

CHANGELOG.md, Cargo.lock, Cargo.toml, cpp/CHANGELOG.md, cpp/Cargo.toml
* `resolvo_cpp`: 0.1.0
* `resolvo`: 0.6.1 -> 0.6.2
<blockquote>
- release-plz resolvo_cpp
- add rattler-build recipe ([#47](https://github.com/mamba-org/resolvo/pull/47))
- c++ bindings ([#41](https://github.com/mamba-org/resolvo/pull/41))
- update README example and capabilities
- resolvo banner
- license, ci, readme
- readme link
- typos
- build badge
- add projects using resolvo
- Show the docs badge ([#12](https://github.com/mamba-org/resolvo/pull/12))
- update banner
- add crates badge
- break out tests to integration test
</blockquote>
<blockquote>
- release-plz resolvo_cpp
- add rattler-build recipe ([#47](https://github.com/mamba-org/resolvo/pull/47))
- c++ bindings ([#41](https://github.com/mamba-org/resolvo/pull/41)) …
=> chore: release

cpp/tests/solve.cpp
minor fix in display_merged_solvables so that it displays them correctly. without this fix a merged solvable is displayed as "a21" as opposed to "a 2 | 1".
=> fix: display_merged_solvables to display merged solvables correctly

cpp/include/resolvo_dependency_provider.h, cpp/tests/solve.cpp
When subclassing `DependencyProvider`, I currently get this warning:
```
warning: base class 'struct resolvo::DependencyProvider' has accessible non-virtual destructor [-Wnon-virtual-dtor]
53 | struct PackageDatabase : public DependencyProvider {
|        ^~~~~~~~~~~~~~~
```
I think any base class which has at least one virtual function, must have virtual destructor to respect class polymorphism.
=> fix: Add a virtual destructor to `DependencyProvider`

src/internal/mapping.rs
Fixes an off-by-one error in the implementation of `Mapping::serialize`, and adds a serialization test (which runs under the `serde` feature) as well.
=> fix: Fix off-by-one error in `Mapping::serialize`

cpp/include/resolvo.h, cpp/include/resolvo_dependency_provider.h, cpp/src/lib.rs, cpp/tests/solve.cpp, src/internal/id.rs, src/lib.rs, src/problem.rs, src/requirement.rs, src/snapshot.rs, src/solver/cache.rs, src/solver/clause.rs, src/solver/mod.rs, src/solver/watch_map.rs, src/utils/pool.rs, tests/snapshots/solver__snapshot.snap, tests/snapshots/solver__snapshot_union_requirements.snap, tests/solver.rs, tools/solve-snapshot/src/main.rs
This PR introduces the concept of _version set unions_ and allows them to be used to specify solvable requirements that can be fulfilled by more than one version set (belonging to more than one package).
The change is facilitated by the introduction of a `Requirement` type, which is used instead of `VersionSetId`s to specify a required dependency of a solvable. A requirement can either be comprised of a single version set (a `VersionSetId`), or multiple version sets (a `VersionSetUnionId`). This allows existing code bases to continue using a single version set (`VersionSetId`) as a requirement specification without ever having to touch version set unions (`VersionSetUnionId`).
This PR introduces _breaking_ changes - the main ones being the following:
- Added the …
=> feat!: Version set unions as solvable requirements

cpp/include/resolvo.h, cpp/src/lib.rs, cpp/tests/solve.cpp, src/conflict.rs, src/lib.rs, src/solver/decision_tracker.rs, src/solver/mod.rs, tests/solver.rs
Adds a new `Solver::solve_with_additional` method, that solves for the provided `root_requirements` and `root_constraints`, along with a set of additional (optional) solvables. Unless the corresponding package has been requested by a version set in another solvable's clauses, each additional solvable is _not_ subject to the package-level clauses introduced in `DependencyProvider::get_candidates` since the solvables have been requested specifically (and not through a version set).
This feature is useful for situations where you want to ensure that particular solvables (for example, previously installed solvables) are compatible with the solution to the root requirements and constraints.
The implementation is facilitated by making the `run_sat` method solve for arbitrary solvables at …
=> feat(solver)!: Solve for optional solvables in addition to the root solvable

CHANGELOG.md, Cargo.lock, Cargo.toml, cpp/Cargo.toml
* `resolvo`: 0.6.2 -> 0.7.0
<blockquote>
- *(solver)* [**breaking**] Solve for optional solvables in addition to the root solvable ([#54](https://github.com/mamba-org/resolvo/pull/54))
- [**breaking**] Version set unions as solvable requirements ([#56](https://github.com/mamba-org/resolvo/pull/56))
- Fix off-by-one error in `Mapping::serialize` ([#58](https://github.com/mamba-org/resolvo/pull/58))
- *(ci)* bump prefix-dev/rattler-build-action from 0.2.12 to 0.2.13 ([#59](https://github.com/mamba-org/resolvo/pull/59))
- *(ci)* bump prefix-dev/rattler-build-action from 0.2.11 to 0.2.12 ([#57](https://github.com/mamba-org/resolvo/pull/57))
- Add more tracing ([#55](https://github.com/mamba-org/resolvo/pull/55))
- *(ci)* bump …
=> chore: release v0.7.0

cpp/src/lib.rs, src/solver/mod.rs, tests/solver.rs
Changes the `Problem` input struct (introduced in #54) to use the builder pattern.
This allows the `soft_requirements` field to be an `Iterator` rather than a `Vec`, which prevents having to unnecessarily clone the `SolvableId`s passed to `soft_requirements` (which in some cases could be on the order of hundreds of thousands). Also, this prevents adding a new input argument to `Solver::solve` (i.e. a new field in `Problem`) from being a breaking change.
The C++ bindings remain unchanged and rely on using a simple `resolvo_cpp::Problem` struct as before; they do not expose the builder pattern.
=> feat(solver)!: Make `Problem` use builder pattern

CHANGELOG.md, Cargo.lock, Cargo.toml, cpp/Cargo.toml
* `resolvo`: 0.7.0 -> 0.8.0
<blockquote>
- [**breaking**] decide on explicit requirements first ([#61](https://github.com/mamba-org/resolvo/pull/61))
- add better timing notebook and measuring ([#64](https://github.com/mamba-org/resolvo/pull/64))
- *(solver)* [**breaking**] Make `Problem` use builder pattern ([#62](https://github.com/mamba-org/resolvo/pull/62))
</blockquote>
</p></details>
---
=> chore: release v0.8.0

Cargo.lock, Cargo.toml, src/conflict.rs, src/internal/arena.rs, src/internal/id.rs, src/internal/mapping.rs, src/solver/clause.rs, src/solver/decision_map.rs, src/solver/decision_tracker.rs, src/solver/mod.rs, src/solver/watch_map.rs, tests/snapshots/solver__merge_installable.snap, tests/snapshots/solver__unsat_after_backtracking.snap, tests/snapshots/solver__unsat_applies_graph_compression.snap, tests/snapshots/solver__unsat_bluesky_conflict.snap, tests/snapshots/solver__unsat_incompatible_root_requirements.snap, tests/snapshots/solver__unsat_pubgrub_article.snap, tests/solver.rs
This branch adds several optimizations. From large impact to small they are:
* We implement two watch literals by monitoring literals now instead of solvables. This removes a lot of unnecessary work.
* It refrains from adding forbidden clauses for packages that will never be selected anyway. This reduces the number of clauses and thus improving backtracking performance. 
* We also reduced the memory size of clauses from 24 to 16 bytes per clause, improving cache locality.
* Furthermore we investigated forcibly inlining certain code paths which also showed a small performance improvement.
=> perf: visit less clauses during propagation

src/solver/mod.rs
This PR implements a form of Variable State Independent Decaying Sum (VSIDS) used in many modern solvers. 
**Background**
VSIDS attempts to score each variable with an activity score and decaying the value over time. During decision time a literal is chosen with the highest activity score. Variables' activity score increases when they are part of a conflict. All variables' activity scores decrease after _n_ conflict by multiplying them with a certain _decay factor_. 
Different solvers have slightly different implementations, the amount by which the activity score is increased, the decay factor, after how many conflicts the activities decay, and which variables are increased as part of the conflict.
I found this a good read: https://ar5iv.labs.arxiv.org/html/1506.08905
**Implementation …
=> perf: implement a form of VSIDS

CHANGELOG.md, Cargo.lock, Cargo.toml, cpp/Cargo.toml
* `resolvo`: 0.8.0 -> 0.8.1 (✓ API compatible changes)
<blockquote>
- implement a form of VSIDS ([#67](https://github.com/mamba-org/resolvo/pull/67))
- *(ci)* bump prefix-dev/rattler-build-action from 0.2.13 to 0.2.14 ([#65](https://github.com/mamba-org/resolvo/pull/65))
- visit fewer clauses during propagation ([#66](https://github.com/mamba-org/resolvo/pull/66))
</blockquote>
</p></details>
---
=> chore: release v0.8.1

Cargo.lock, cpp/CMakeLists.txt, cpp/Cargo.toml
Fixes where the libraries and binaries are placed.
=> fix: use GNUInstallDirs for installation locations

src/conflict.rs, src/snapshot.rs, tests/snapshots/solver__root_constraints.snap, tests/solver.rs, tools/solve-snapshot/src/main.rs
This fixes an issue that Jaime found in his work on `conda-rattler-solver`. 
In conda-rattler-solver a lot more constraints are used then we generally do in pixi and other projects, so this became apparent quite quickly.
I haven't been able to verify whether the message makes a lot of sense yet, though.
=> fix: constraint at root can conflict

CHANGELOG.md, Cargo.lock, Cargo.toml, cpp/Cargo.toml
* `resolvo`: 0.8.2 -> 0.8.3 (✓ API compatible changes)
<blockquote>
- constraint at root can conflict ([#79](https://github.com/mamba-org/resolvo/pull/79))
- *(ci)* bump prefix-dev/rattler-build-action from 0.2.16 to 0.2.18 ([#78](https://github.com/mamba-org/resolvo/pull/78))
- *(ci)* bump prefix-dev/rattler-build-action from 0.2.15 to 0.2.16 ([#75](https://github.com/mamba-org/resolvo/pull/75))
</blockquote>
</p></details>
---
=> chore: release v0.8.3

CHANGELOG.md, Cargo.lock, Cargo.toml, cpp/Cargo.toml
* `resolvo`: 0.8.3 -> 0.8.4 (✓ API compatible changes)
<blockquote>
- constraint formatting ([#80](https://github.com/mamba-org/resolvo/pull/80))
</blockquote>
</p></details>
---
=> chore: release v0.8.4

src/internal/id.rs, src/internal/mapping.rs, src/solver/clause.rs, src/solver/mod.rs, src/solver/watch_map.rs
Reduce the memory consumption of the `WatchMap` by utilizing `NonZeroU32`. Rust has an optimization that an `Option<NonZero..>` is the same size as a `NonZero..`. The optimization uses the fact that `0` means `None`. 
Our `Mapping` type stores `Option<T>`. The `WatchMap` contains a `Mapping<Literal, ClauseId>`. For each `Literal` we store an `Option<ClauseId>`. Previously we would encode a `null` clause as `ClauseId::null`. We now store this as an `Option<ClauseId>`.
This reduces the memory size of an `Option<ClauseId>` from 8 bytes to 4 bytes. It reduces the memory usage of the watchmap by 50% and makes working with a null clause more ergonomic.
I didnt run the benchmarks but I am quite confident that there will be no negative impact.
=> refactor: reduce watchmap memory size

src/solver/mod.rs, tests/solver.rs
Fixes #90 
Fixes a crash that was caused by a union requirement with a last term that had no candidates. I added a test that crashes on main and succeeds with this PR.
=> fix: crash when a union requirement has no candidates

CHANGELOG.md, Cargo.lock, Cargo.toml, cpp/Cargo.toml
* `resolvo`: 0.8.4 -> 0.8.5 (✓ API compatible changes)
<blockquote>
- issue where a union clause has no candidates (#93)
- reintroduce binary encoding of forbid multiple clauses (#91)
- reduce watchmap memory size (#92)
- *(ci)* bump prefix-dev/rattler-build-action from 0.2.19 to 0.2.25 (#89)
- *(ci)* bump prefix-dev/rattler-build-action from 0.2.18 to 0.2.19 (#82)
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
=> chore: release v0.8.5

src/internal/id.rs, src/internal/mod.rs, src/internal/unwrap_unchecked.rs, src/solver/clause.rs, src/solver/mod.rs, src/solver/watch_map.rs
This PR cleans up the code by adding a new type for traversing and modifying the watchmap. The propagation loop contained a number of bookkeeping locals which distract from the actual propagation algorithm. There were also methods to manipulate the watches and the watchmap in different places, they are now all consolidated in the `WatchMapCursor` struct. 
Using the cursor is very simple: `WatchMap::cursor` is used to create a cursor to iterate the linked list of watches. `WatchMapCursor::next` moves the cursor to the next clause watching a certain literal. `WatchMapCursor::update` modifies the current clause/watch to watch a different literal. This method performs all the bookkeeping of the linked lists to ensure consistency.
Hopefully this makes the code easier to understand.
=> refactor: simplify watchmap traversal

src/solver/mod.rs
Run this new test by itself with `cargo test test_tracing`.
When tracing is configured with multiple output channels, it is possible for the `tracing::debug!` macro to call `fmt` multiple times on its arguments.
`format_with` is documented to panic if formatted more than once. https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.format_with
The panic can be avoided by adding `.to_string()` to the end of the use of `format_with` around line 569 of solver/mod.rs, but this may not be the best fix.
This test sets a global default which conflicts with tracing_test, so this new test doesn't play nice with the other tests when running the whole test suite.
Edit:
Test removed and the `to_string` fix has been put in place instead.
=> Avoid panic in Itertools::format_with

.github/workflows/cpp-test.yml, .github/workflows/enforce-sha.yaml, .github/workflows/release-plz.yml, .github/workflows/rust-compile.yml
- pin external actions
- enforce sha also in the future
For motivation see https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised and https://michaelheap.com/pin-your-github-actions/
=> ci: pin github actions

cpp/src/lib.rs, src/lib.rs, src/snapshot.rs, src/solver/cache.rs
This PR adds an enum for `hint_dependencies_available` so that if dependencies are available for all dependencies there is no need to duplicate a vec.
=> feat: add type for `HintDependenciesAvailable`

CHANGELOG.md, Cargo.lock, Cargo.toml, cpp/Cargo.toml
* `resolvo`: 0.8.6 -> 0.8.7 (✓ API compatible changes)
<blockquote>
- add type for `HintDependenciesAvailable` ([#123](https://github.com/prefix-dev/resolvo/pull/123))
- *(ci)* bump zgosalvez/github-actions-ensure-sha-pinned-actions ([#119](https://github.com/prefix-dev/resolvo/pull/119))
- *(ci)* bump MarcoIeni/release-plz-action from 0.5.100 to 0.5.104 ([#121](https://github.com/prefix-dev/resolvo/pull/121))
- *(ci)* bump prefix-dev/setup-pixi from 0.8.3 to 0.8.7 ([#122](https://github.com/prefix-dev/resolvo/pull/122))
- pin follow up ([#116](https://github.com/prefix-dev/resolvo/pull/116))
- pin github actions ([#115](https://github.com/prefix-dev/resolvo/pull/115))
- *(ci)* bump prefix-dev/setup-pixi from 0.8.1 to 0.8.3 …
=> chore: release v0.9.0

.github/workflows/cpp-test.yml
We got the following error in CI
> This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101
This PR bumps the runner to use ubuntu 22.04.
=> fix: bump ubuntu runner version

src/conflict.rs, src/internal/mapping.rs, src/solver/clause.rs, src/solver/decision_map.rs, src/solver/decision_tracker.rs, src/solver/mod.rs, src/solver/watch_map.rs
This PR cleans up the ownership of state in the solver
=> refactor: clean-up ownership

src/internal/id.rs, src/solver/encoding.rs, src/solver/mod.rs, src/solver/variable_map.rs
This PR refactors how we get information from the dependency provider and encode the information into sat clauses. Functionally nothing changes but I refactored the `add_clauses_for_solvables` method into an object to make it much clearer what the code flow is.
=> refactor: encoding of clauses

cpp/CMakeLists.txt, cpp/Cargo.toml
This PR renames the import lib name on windows from `resolvo_cpp.dll.lib` to `resolvo_cpp.lib`. This is required to make rattler-build recognize this as the import library associated with the dll.
=> fix: import lib name
